### ISSUE TITLE
`DiscordResponseParser::parseResponse` MisMatchedInputException with successful response

### ISSUE THREAD

**Issue by NightTripperID** [javadiscord/java-discord-api#103]
## Description of the Issue
`DiscordResponseParser::parseResponse` throws `MismatchedInputException` when trying to deserialize audit logs from response json

[valid_response.json](https://github.com/javadiscord/java-discord-api/files/15367006/valid_response.json)

```
return objectMapper.readValue(
                response,
                objectMapper.getTypeFactory().constructCollectionType(List.class, elementType));
```
## Reproduction Steps
**Steps to reproduce the behavior**:
- From example bot, trigger guild invite by sending a message in channel
- Observe error logs

**Expected behavior**
The response parser should successfully parse the audit logs (or any other list) from the response json

## Acceptance Criteria

**WHEN** the bot receives a response
**THEN** the audit logs should successfully parse into `List<AuditLog>`

**Comment by SquidXTV** [comment]
fixed by #113
