### ISSUE TITLE
`GatewayEventListener::getGuild` fails to deserialize guild id when the id comes as a String from Discord

### ISSUE THREAD

**Issue by NightTripperID** [javadiscord/java-discord-api#104]
## Description of the Issue
Discord normally sends guild id as a long, but occasionally sends it as a String. This is the case when Discord notifies of a pinned or unpinned message, and perhaps for other events.

## Reproduction Steps
**Steps to reproduce the behavior**:
- have the bot observe a "message pinned" or "message unpinned" event
- observe error logs

**Expected behavior**
`GatwayEventListener::getGuild` should use branching logic to successfully deserialize guild id via reflection regardless of whether it arrives as a String or a long

## Acceptance Criteria
**WHEN** the bot receives an event payload with guild id as a String or a long
**THEN** `GatewayEventListener::getGuild` should successfully deserialize guild id

**Comment by SquidXTV** [comment]
fixed by #108
