### ISSUE TITLE
`DiscordResponseParser::parseResponse`:  `MisMatchedInputException` with error response

### ISSUE THREAD

**Issue by NightTripperID** [javadiscord/java-discord-api#106]
## Description of the Issue
`DiscordResponseParser::parseResponse` fails to deserialize an error message when receiving a response with a 4xx HTTP code. It tries to deserialize a json body into a list, but the json body only has two fields:

```
{
  "message": "Missing Permissions",
  "code": 50013
}
```

```
return objectMapper.readValue(
                response,
                objectMapper.getTypeFactory().constructCollectionType(List.class, elementType));
```

## Reproduction Steps
- perform a request for which the bot has insufficient permissions
- observe error logs

**Expected behavior**
`DiscordResponseParser::parseResponse` should successfully deserialize the error message

## Acceptance Criteria
**WHEN** the bot receives an error response
**THEN** `DiscordResponseParser::parseResponse` should successfully deserialize the response json

**Comment by SquidXTV** [comment]
fixed by #113
