### ISSUE TITLE
`HttpRequestBuilder.PUT` throws `NullPointerException` when no body is specified

### ISSUE THREAD

**Issue by NightTripperID** [javadiscord/java-discord-api#107]
## Description of the Issue
When an `HttpRequest` is built using a  bodyless `DiscordRequestBuilder` for a PUT, it throws `NullPointerException`

## Reproduction Steps
- Perform a `DiscordRequest` that does not require a body and uses a PUT, such as "pin message"
- Observe error logs

**Expected behavior**
When an `HttpRequest` for a PUT is built from a bodyless `DiscordRequestBuilder`, the object should build successfully and not throw `NullPointerException`
This can be achieved by adding `.body(HttpRequest.BodyPublishers.noBody())` to all `DiscordRequest::create` implementations that lack a body and are used in a PUT

## Acceptance Criteria

**WHEN** `HttpRequest::PUT` is called
**THEN** a `NullPointerException` should not be thrown

**Comment by SquidXTV** [comment]
Going to take care of this
