### ISSUE TITLE
Update cache using `DiscordResponseParser`

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#111]
When we parse requests using `DiscordResponseParser`, this is a good time for us to update our cache as we currently only update on gateway events. 

```java
    private <T> void success(
            Class<T> type, DiscordResponse response, AsyncResponse<T> asyncResponse) {
        if (response.status() >= 200 && response.status() < 300) {
            try {
                T result = OBJECT_MAPPER.readValue(response.body(), type);
                asyncResponse.setResult(result);
            } catch (JsonProcessingException e) {
                asyncResponse.setException(e);
            }
        } else {
            asyncResponse.setException(
                    new Exception(
                            "Received HTTP status code "
                                    + response.status()
                                    + " "
                                    + response.body()));
        }
    }
```

This is our current code for when we fully receive a response from discord. We can leverage the `T result` to call the cache and update. Using reflection we can grab the object ID and then run `cache.add(id, result);`

**Acceptance Criteria**
WHEN sending a request to discords API
AND we receive a success status code
THEN we should update our cache with the retrieved object

**Comment by NightTripperID** [comment]
I'd like to take this one up
