### ISSUE TITLE
Recommendation: Free Open Source GitHub Security Engineer plugin - Pixeebot assists Hardening Code, Fixing Bugs & addressing Sonar Issues

### ISSUE THREAD

**Issue by pixeeai** [javadiscord/java-discord-api#129]
Meet your automated product security engineer
Pixeebot fixes vulnerabilities, hardens code, squashes bugs, and gives engineers more time to focus on the work that counts.

More Details:
https://github.com/apps/pixeebot

**Comment by pixeeai** [comment]
I just forked your repo & this was the first recommendation the bot came up with:

[Introduced protections against "zip slip" attacks](https://github.com/Pixee-Bot-Java/java-discord-api/pull/1)

**Comment by surajkumar** [comment]
@pixeebot next

**Comment by surajkumar** [comment]
Fixed

**Comment by pixeeai** [comment]
@pixeebot next

**Comment by pixeeai** [comment]
@surajkumar were you able to get it installed successfully on your repository?

**Comment by surajkumar** [comment]
Yeah, thanks for raising the issue. It's not a good idea for me to include your dependency into my repository for a very small fix so we coded that ourselves. 

This was an issue that Sonar had already raised with suggested fixes prior to Pixeeai hence why.

**Comment by pixeeai** [comment]
@surajkumar No worries. We also recommend many changes that don't include dependency additions. Were you able to try to get it installed via the GitHub Marketplace?

Here is the link:
https://github.com/apps/pixeebot
