### ISSUE TITLE
[suggestion] Free Security Plugin, Pixeebot

### ISSUE THREAD

**Issue by pixeeai** [javadiscord/java-discord-api#158]
### What would you like to change?
Pixeebot helps improve project's codebase via opening PRs to help improve code security, common vulnerabilities, common Sonar/CodeQL issues & more.

### How do you think that would improve the project?
It will offset part of the developers' workloads by working alongside to squash bugs and composals to fix them as well.
The Pixeebot plugin is located within the GitHub marketplace -> [Install Here](https://github.com/apps/pixeebot)

## Context

 More details -> https://pixee.ai

**Comment by surajkumar** [comment]
Rejected due to the current suite of scanning is adequate.

**Comment by pixeeai** [comment]
> Rejected due to the current suite of scanning is adequate.

Here are the reccomendation PRs that have been scanned so far:
- [Introduced protections against "zip slip" attacks](https://github.com/Pixee-Bot-Java/java-discord-api/pull/1)
- [Modernize and secure temp file creation](https://github.com/Pixee-Bot-Java/java-discord-api/pull/2)
