### ISSUE TITLE
Implement discords channel API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#22]
## As a user I want to...
be able to call the [channel](https://discord.com/developers/docs/resources/channel) endpoints

## So that...
I can perform channel actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with channels in a discord server. We should implement all these endpoints. This ticket covers only the Channel endpoints. https://discord.com/developers/docs/resources/channel

## Acceptance Criteria
GIVEN a user wants to send a request to interact with a channel on discord
THEN the specified action should be executed with sufficent error logging in place

**Comment by surajkumar** [comment]
**Currently implement**:

* BulkDeleteMessagesRequest
* ChannelCreateInviteRequest
* CreateMessageRequest
* CreateReactionRequest
* CrossPostMessageRequest
* DeleteAllReactionsForEmojiRequest
* DeleteAllReactionsRequest
* DeleteChannelRequest
* DeleteMessageRequest
* DeleteOwnReactionRequest
* DeleteUserReactionRequest
* EditMessageRequest
* FetchChannelMessageRequest
* FetchChannelMessagesRequest
* FetchChannelRequest
* FetchUserReactionsToMessageRequest
* ModifyChannelRequest

**Remaining**; 

- Get Channel Messages
- Get Channel Message
- Delete/Close Channel
- Edit Channel Permissions
- Get Channel Invites
- Delete Channel Permission
- Follow Announcement Channel
- Trigger Typing Indicator
- Get Pinned Messages
- Pin Message
- Unpin Message
- Group DM Add Recipient
- Group DM Remove Recipient
- Start Thread from Message
- Start Thread without Message
- Start Thread in Forum or Media Channel
- Join Thread
- Add Thread Member
- Leave Thread
- Remove Thread Member
- Get Thread Member
- List Thread Members
- List Public Archived Threads
- List Private Archived Threads
- List Joined Private Archived Threads
-

**Comment by tferdous17** [comment]
I'd like to be assigned to this.
