### ISSUE TITLE
Implement discords guild API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#24]
## As a user I want to...
be able to call the [guild](https://discord.com/developers/docs/resources/guild) endpoints

## So that...
I can perform guil actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with guilds in a discord server. We should implement all these endpoints. This ticket covers only the Channel endpoints. https://discord.com/developers/docs/resources/guild

## Acceptance Criteria
GIVEN a user wants to send a request to interact with a guild on discord
THEN the specified action should be executed with sufficent error logging in place

**Comment by nateweisz** [comment]
Can I be assigned to this?

**Comment by nateweisz** [comment]
Does this include the get guild member requests too? or just the get, create, modify and delete requests for the guild?

**Comment by surajkumar** [comment]
> Does this include the get guild member requests too? or just the get, create, modify and delete requests for the guild?

Yes please - everything under the guild section
