### ISSUE TITLE
Implement discords Guild Scheduled Event API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#30]
## As a user I want to...
be able to call the [Guild Scheduled Event](https://discord.com/developers/docs/resources/guild-scheduled-event) endpoints

## So that...
I can perform channel actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with guild scheduled events in a discord server. We should implement all these endpoints. This ticket covers only the Guild Scheduled Event endpoints. https://discord.com/developers/docs/resources/guild-scheduled-event

## Acceptance Criteria
GIVEN a user wants to send a request to interact with a Guild Scheduled Event on discord
THEN the specified action should be executed with sufficent error logging in place

**Comment by nateweisz** [comment]
May I be assigned to this?
