### ISSUE TITLE
Implement discords stage instance API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#31]
## As a user I want to...
be able to call the [stage instance](https://discord.com/developers/docs/resources/stage-instance) endpoints

## So that...
I can perform stage instance actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with stage instance in a discord server. We should implement all these endpoints. This ticket covers only the stage instance endpoints. https://discord.com/developers/docs/resources/stage-instance

## Acceptance Criteria
GIVEN a user wants to send a request to interact with a stage instance on discord
THEN the specified action should be executed with sufficent error logging in place

**Comment by nateweisz** [comment]
May I be assigned to this?

**Comment by surajkumar** [comment]
Certainly,  thank you!

**Comment by nateweisz** [comment]
> Certainly, thank you! Set the status to in progress whenever you're ready :)

I don't believe I have permission to edit the board.
