### ISSUE TITLE
Implement discords Auto Moderation API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#36]
## As a user I want to...
be able to call the [Auto Moderation](https://discord.com/developers/docs/resources/auto-moderation) endpoints

## So that...
I can perform Auto Moderation actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with channels in a discord server. We should implement all these endpoints. This ticket covers only the Auto Moderation endpoints. https://discord.com/developers/docs/resources/auto-moderation

## Acceptance Criteria
GIVEN a user wants to setup auto moderation rules
THEN the specified auto moderation rule should be applied

**Comment by nateweisz** [comment]
May I be assigned?
