### ISSUE TITLE
Higher Level API: ModifyScheduledEventRequest Note

### ISSUE THREAD

**Issue by nateweisz** [javadiscord/java-discord-api#45]
## Description of the Issue
If updating entityType to EXTERNAL:
    channelId must be set to null
    entityMetadata with a entityMetadata field must be provided
    scheduledEndTime must be provided

There should likely be some validation provided at a higher level.

**Comment by surajkumar** [comment]
Related PR: https://github.com/javadiscord/java-discord-api/pull/44
