### ISSUE TITLE
Implement Application API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#59]
## As a user I want to...
be able to call the [application](https://discord.com/developers/docs/resources/application) endpoints

## So that...
I can perform application-role-connection-metadata actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with application in a discord server. We should implement all these endpoints. This ticket covers only the application. https://discord.com/developers/docs/resources/application

## Acceptance Criteria
GIVEN a user wants to send a request to interact with a application on discord
THEN the specified action should be executed with sufficent error logging in place

**Comment by tferdous17** [comment]
I'd like to be assigned to this.
