### ISSUE TITLE
Proposal: Automatic Enum serializer

### ISSUE THREAD

**Issue by nateweisz** [javadiscord/java-discord-api#65]
The models we have right now, `Guild`, `Member`, and more use int's to represent enum's. Although I am not clear as to if these will be user facing models or internal. It seems like quite a hassle to not use these as user facing models and easier to maintain.

If we would like to have these as user facing models I propose that we write a annotation processor that automatically generates the "codec" for each enum and that instead of having it represented as an int inside the model we would have it as the enum that it represents.

**Comment by surajkumar** [comment]
I agree with this, let's action it

**Comment by nateweisz** [comment]
We discussed on discord and we can just annotate the getValue method in our enums with @JsonValue
