### ISSUE TITLE
Implement Guild Template API

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#81]
## As a user I want to...
be able to call the [guild template](https://discord.com/developers/docs/resources/guild-template) endpoints

## So that...
I can perform guild template actions using my discord bot

## Context
Discord provides a rich set of APIs for interacting with guild template in a discord server. We should implement all these endpoints. This ticket covers only the guild template endpoints. https://discord.com/developers/docs/resources/guild-template

## Acceptance Criteria
GIVEN a user wants to send a request to interact with a guild template on discord
THEN the specified action should be executed with sufficent error logging in place

**Comment by notyourhabibti** [comment]
hello, please can I pick this up? x
