### ISSUE TITLE
Add a stop() method to the `Discord` class

### ISSUE THREAD

**Issue by surajkumar** [javadiscord/java-discord-api#98]
## As a user I want to...

be able to stop the discord service after I have started it

## So that...

we I can stop what I have started

## Context

We have a start method that starts all of bot services but nothing to shut down.

## Acceptance Criteria
GIVEN the start() has been called
AND the stop() has been called after calling start()
THEN then all threads, connections etc should be shutdown

**Comment by mennafabio** [comment]
Hey! I would love to implement this one.

**Comment by surajkumar** [comment]
> Hey! I would love to implement this one.

Thanks! I'll assign it to you

**Comment by mennafabio** [comment]
PR is open https://github.com/javadiscord/java-discord-api/pull/100
